# Generated by Django 6.0.4 on 2026-04-13 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=8, null=True)),
                ('measurement', models.CharField(blank=True, help_text='e.g., 5kg bag, 1 liter bottle, etc.', max_length=100)),
                ('supplier_name', models.CharField(blank=True, max_length=200)),
                ('supplier_location', models.CharField(blank=True, max_length=200)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='products/main/')),
                ('additional_image_1', models.ImageField(blank=True, null=True, upload_to='products/additional/')),
                ('additional_image_2', models.ImageField(blank=True, null=True, upload_to='products/additional/')),
                ('additional_image_3', models.ImageField(blank=True, null=True, upload_to='products/additional/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_type', models.CharField(choices=[('seeds', 'Seeds'), ('fertilizers', 'Fertilizers'), ('tools', 'Farm Tools'), ('livestock', 'Livestock'), ('fresh_produce', 'Fresh Produce'), ('processed', 'Processed Foods'), ('pesticides', 'Pesticides'), ('other', 'Other')], default='other', max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['id', 'slug'], name='shop_produc_id_f21274_idx'), models.Index(fields=['name'], name='shop_produc_name_a2070e_idx'), models.Index(fields=['-created_at'], name='shop_produc_created_ddfb00_idx')],
            },
        ),
    ]
